### ISSUE TITLE
mq-dev-config file is not copied over to /etc/mqm/ change required in Dockerfile

### ISSUE THREAD

**Issue by amitvjoshi** [ibm-messaging/mq-docker#118]
https://github.com/ibm-messaging/mq-docker/blob/ef46353e396ea0eeed324c058f64932e34483760/mq-dev-config.sh#L126

**Comment by parrobe** [comment]
Hi @amitvjoshi,

This repository is now deprecated and has been replaced by the MQ-container repository. We’ve made improvements to how the MQ developer defaults are set in that repo and strongly suggest you use that repo instead of MQ-docker.

I’ve taken a look at the line you have pointed out, the Dockerfile does do a copy to move the MQ-dev-config file to the container image under ‘/etc/mqm’ as such I’m not sure what changes need to be made. 

As this repo is deprecated and I believe the code is correct and requires no further changes I’ll be closing this issue. If you disagree please explain what changes need to be made.

**Comment by amitvjoshi** [comment]
pls close it I see the code, my bad. 
COPY mq-dev-config /etc/mqm/mq-dev-config
