### ISSUE TITLE
Not obvious how to get `mqconfig` to pass

### ISSUE THREAD

**Issue by arthurbarr** [ibm-messaging/mq-docker#13]
The `mqconfig` command gets run when the container starts, and frequently indicates a problem with the host environment.  There is a link in the README to the MQ documentation on preparing your host, but this is not obvious to find, or to follow what you need to do.  This issue is to improve the README and/or add some help messages in the case of an `mqconfig` failure.

**Comment by cmebarrow** [comment]
When using Docker toolbox on Mac or Windows the container indicates a problem with the file-max setting. The following steps will resolve this (they also cover the initial installation of docker toolbox)
- Install [Docker Toolbox for Windows](https://docs.docker.com/engine/installation/windows/) or [Docker Toolbox for Mac](https://docs.docker
.com/engine/installation/mac/)
- Make sure the directory where docker toolbox was installed is in your PATH (e.g. C:\Program Files\Docker Toolbox)
- Start docker-machine from a command prompt window if not already started. Refer to the above docker toolbox links for instructions. Usually the following command should suffice:
  - docker-machine start
- Then set up the required environment in a command prompt window:
  - docker-machine env
  - Follow the printed instructions to set the DOCKER_xxx environment variables
- Now run the following commands to increase file-max to the value required by MQ:
  - docker-machine ssh
  - sudo sysctl -w fs.file-max=524288
  - exit
Unfortunately the above docker-machine ssh and sudo sysctl -w fs.file-max=524288 needs to be done each time you restart the docker engine (docker-machine), including if you reboot your machine. This is because docker-machine does not currently support permanently changing any of the Linux kernel parameters.

**Comment by cmebarrow** [comment]
On Linux, one runs into shmmax not being sufficiently high (at least on Debian the default is lower than the MQ requirement reported by mqconfig). Here are notes from my colleague @ahousing:

> There is a bug in docker [[1](https://groups.google.com/d/msg/docker-dev/HTC_q92ILZs/hMyxN53fpKQJ), [2](https://github.com/docker/docker/issues/4717), [3](https://github.com/docker/docker/pull/19265)] that forces the shmmax to 32Mb.  The workaround to that is to pass "--priveleged=true" to the "docker run" command, and then modify the shmmax size with "sysctl -w kernel.shmmax=268435456". 

This would have to be done before the entry point script of the mq-docker is executed, probably by creating a new docker image extending the mq-docker image and overriding the ENTRYPOINT with a call to "sysctl -w kernel.shmmax=268435456" followed by a call to the original  entry point "mq.sh".

We are working on trying this approach now. Has anyone else successfully done this?

**Comment by arthurbarr** [comment]
The values specified by `mqconfig` were originally designed for a bare metal server with two queue managers.  The values are not really appropriate for running in a Docker container.  For now, we have taken the decision to remove the use of `mqconfig`.  In the future, we may re-instate a more sensible set of values, but the use of `mqconfig` has so far been the biggest pain point of using the MQ Docker image.
