### ISSUE TITLE
AMQ7017: Log not available errors

### ISSUE THREAD

**Issue by usuresh80** [ibm-messaging/mq-docker#41]
I am not sure whether I can call this as an error, seems I am missing some thing in deploying this one
I am using windows 7 as my host machine and installed docker tool kit  to run docker images 

I have ran below commands to run this image 

docker build --tag mq ./server/  // to pull and install mq 
created config.mqsc  and Dockerfile in separate directory   and ran build command again  as below 
docker build --tag mymq .

I have one question here , I did not change any content in  Dockerfile
FROM mq
RUN useradd mquser -G mqm && \
    echo mquser:abc123 | chpasswd
COPY config.mqsc /etc/mqm/

// here can I use /etc/mqm as host is windows ?

and run this image  as below 

docker run --env LICENSE=accept --ipc host --env MQ_QMGR_NAME=QM1 --volume //C/Temp/mq:/var/mqm --publish 1414:1414  mymq

out put of above command is 
total 12
drwxrwsr-x 2 mqm mqm   40 Jan 28 23:37 config
drwxrwsr-x 3 mqm mqm   60 Jan 28 23:37 conv
drwxrwsrwx 2 mqm mqm  220 Jan 29 16:32 errors
drwxrwsr-x 2 mqm mqm   40 Jan 28 23:37 exits
drwxrwsr-x 2 mqm mqm   40 Jan 28 23:37 exits64
drwxrwsr-x 3 mqm mqm   60 Jan 28 23:37 log
-rw-rw-r-- 1 mqm mqm  637 Jan 28 23:37 mqclient.ini
drwxrwsr-x 5 mqm mqm  100 Jan 28 23:37 mqft
-rw-rw-r-- 1 mqm mqm 2604 Jan 28 23:37 mqs.ini
drwxrwsr-x 4 mqm mqm   80 Jan 28 23:37 qmgrs
-rw-rw-r-- 1 mqm mqm 1941 Jan 28 23:37 service.env
drwxrwsr-x 4 mqm mqm   80 Jan 28 23:37 shared
drwxrwsr-x 4 mqm mqm   80 Jan 28 23:37 sockets
drwxrwsrwx 2 mqm mqm   40 Jan 28 23:37 trace
----------------------------------------
Name:        IBM MQ
Version:     9.0.0.0
Level:       p900-L160520.DE
BuildType:   IKAP - (Production)
Platform:    IBM MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 4.4.43-boot2docker
InstName:    Installation1
InstDesc:
Primary:     Yes
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 900
LicenseType: Developer
----------------------------------------
IBM MQ queue manager 'QM1' starting.
The queue manager is associated with installation 'Installation1'.
AMQ7017: Log not available.

what could be   the issue ?, do you have any  reference urls related to windows ?

**Comment by parrobe** [comment]
Hi @usuresh80 - In answer to your question:

> COPY config.mqsc /etc/mqm/
> // here can I use /etc/mqm as host is windows ?

Yes you can. the COPY command takes two parameters. The first is the location of the file on the host and the second is the location of the file on the container. As the container is a Unix container you can use /etc/mqm and it will be placed in the right place.

To answer your other issue i'm afraid i'm not sure why you're getting a AMQ7017 error. It could be a incompatibility with docker for Windows. I'll see if i can reproduce on my windows box (normally i use a Linux VM for developement)

**Comment by kimptoc** [comment]
FWIW Getting same error (also running on Windows via docker toolbox).  Works if I leave off the volume mapping - which obviously means nothing is persisted.  Wonder if there is a compatible windows storage option.

**Comment by arthurbarr** [comment]
With Docker for Windows, you need to explicitly share directories: https://docs.docker.com/docker-for-windows/#shared-drives

If using the older Docker Toolbox for Windows, then I think you can only share volumes from the C:\Users directory (see http://stackoverflow.com/questions/34161352/docker-sharing-a-volume-on-windows-with-docker-toolbox#34255036)

**Comment by raiss** [comment]
Same issue on osx10.13 with docker Version 17.09.0-ce-mac35
I can only get it to work if I remove the Volume Mapping as @kimptoc suggested.

**Comment by arthurbarr** [comment]
@rasii, this works fine for me on the same versions.  The key is which directories you attempt to bind-mount.

Docker for Mac and Docker for Windows work by creating a Linux virtual machine to run the Docker daemon, and then allowing you to connect a Docker client on your host (Mac/Windows) to that daemon.  If you choose to use bind-mounted volumes (i.e. a directory on your host which you want to share with a container), then Docker does this by sharing certain directories over the network with your Linux VM.  For security reasons, not all directories on your host are shared.  So this gives you three options:

1. Use a bind-mounted volume from a pre-shared location (e.g. under your home directory)
2. Configure Docker for [Mac](https://docs.docker.com/docker-for-mac/#file-sharing)/[Windows](https://docs.docker.com/docker-for-windows/#shared-drives) to add additional directories.
3. Use Docker [volumes](https://docs.docker.com/engine/admin/volumes/volumes/) instead of bind-mounting directories.
