### ISSUE TITLE
docker image with perl MQ Series client

### ISSUE THREAD

**Issue by ravi567** [ibm-messaging/mq-docker#77]
Hi: I am trying to build/pull a docker image that has perl with MQSeries module. Is this the right docker image.  All I am trying to is write scripts that connect to a MQ server to send and receive messages. I don't intend to run a MQ server. I have tried including "requires 'MQSeries'" in the cpanfile and tried to build a brand new image. But keep getting "Configure failed for MQSeries-1.34. See /root/.cpanm/work/1497022432.9/build.log for details". Can someone point me in the right direction? Maybe there is a docker image with this already built in it. All my searches have not resulted in something useful. 

Thanks
Ravi

**Comment by parrobe** [comment]
Hi @ravi567 - The image(s) in this repository will probably not meet your requirements as they are right now. They are sample MQ Server Docker images, so for your case where you will be doing client work will not be applicable. 
I'm not aware of any docker images which only build the MQ Client or build the MQ Client with Perl so you will have to create one. I would suggest looking at the sample Dockerfiles here and using the system we use to download and install the IBM MQ Advanced for Developers edition, but modifying it to install the MQ Client binaries you require and other perl binaries (and removing/changing the start up scripts).

Because this repository handles the example IBM MQ Server image we will be unlikely to provide you any support here. I would suggest you try other IBM MQ forums for help such as:

- [Stackoverflow](https://stackoverflow.com/questions/tagged/ibm-mq)
- [MQ Mailing list](https://listserv.meduniwien.ac.at/archives/mqser-l.html)
- or if you have a valid support contact with IBM MQ contacting Support.

**Comment by ravi567** [comment]
thank you.
