### ISSUE TITLE
MQClient in docker container cant put messages via ipc to queue manager on host

### ISSUE THREAD

**Issue by majst01** [ibm-messaging/mq-docker#8]
Hi,

we try to communicate from a docker container with mqclient version 7.5.0.5 installed (Dockerfile is about the same as your MQv8 Docker file. 
MQ Manager 7.5.0.5 is installed on the host native and a qmanager called DKR1 and a local queue DOCKER.TEST.

We start the mq client docker container as followes:
docker run -it --net=host --ipc=host -v /var/mqm:/var/mqm mq-client /bin/bash
in the docker container we try to send a message using the samples via:

export MQCHLLIB=/var/mqm/qmgrs/DKR1/@ipcc/
/opt/mqm/samp/bin/amqsput DOCKER.TEST DKR1
with the following result:
Sample AMQSPUT0 start
MQCONN ended with reason code 2058

The same call from the host did work properly. 
Do you have any hints how we can nail down this problem, we already checked /var/mqm/errors but nothing was written there.

Appreciate any hints
Stefan

**Comment by dnwe** [comment]
Hi @majst01 - apologies for the delay in responding to you, it appears that your issue had been overlooked when it was originally raised. You may have already resolved this by now, but here are some thoughts:

Just to confirm what you're trying to do here:
- you want to connect a client running on the physical host (or within a different container) to the queue manager running within the ibmcom/mq over TCP/IP ?

Assuming that is the case, there are a couple of things here:
1) you ran amqsput rather than amqsputc, was that intentional?
2) you volume mounted the whole /var/mqm tree, but you should probably just provide the .TAB file - i.e., `docker run ... -v /var/mqm/qmgrs/DKR1/@ipcc/AMQCLCHL.TAB:/AMQCLCHL.TAB -e MQCHLTAB=/AMQCLCHL.TAB ...`
3) your ibmcom/mq docker image hostname must be resolvable by your client container for it to be able to communicate using the table information, refer to [docker networking](https://docs.docker.com/v1.11/engine/userguide/networking/dockernetworks/) on how you achieve that. Alternatively you might find it easier to stop using the chltab altogether and use the `MQSERVER` env var to point the client container at the physical host and exposed port for the qmgr, e.g., `export MQSERVER=YOURCLIENTCHL/TCP/'172.17.0.1(1414)'`

**Comment by majst01** [comment]
Hi @dnwe - never mind. We actually enforced all application to only use MQ-Client mode which works from within a container to a outside MQ Server out of the box.
